common/models/Invoice.php
<?php
/**
 * Created with love by Альянс Экспресс.
 * Author: Anochin Nikolay
 * Email: titan12345@mail.ru
 * Phone: +7 925 174 1314
 * Date: 06.07.2018
 * Time: 12:34
 */


namespace common\models;

use common\models\base\InvoiceBase;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;

/**
 * Class Invoice
 * @package common\models
 */
class Invoice extends InvoiceBase
{
    const STATUS_PENDING = 0;
    const STATUS_DELIVERED = 1;
    const STATUS_ON_WAY = 2;
    const STATUS_TAKEN_TO_WAREHOUSE = 3;
    const STATUS_RETURNED = 4;

    /**
     * Статус накладной
     * @return mixed
     */
    public function getStatusLabel()
    {
        return ArrayHelper::getValue(self::getStatusLabels(), $this->status);
    }

    /**
     * Список статусов накладных
     * @return array
     */
    public static function getStatusLabels()
    {
        return [
            self::STATUS_PENDING => 'Ожидает отправки',
            self::STATUS_DELIVERED => 'Доставлено',
            self::STATUS_ON_WAY => 'В пути',
            self::STATUS_TAKEN_TO_WAREHOUSE => 'Принято на склад',
            self::STATUS_RETURNED => 'Возвращен'
        ];
    }

    /** @inheritdoc */
    public function behaviors()
    {
        return [
            'timestamp' => TimestampBehavior::class,
        ];
    }
}

backend/controllers/InvoiceController.php
<?php

namespace backend\controllers;

use common\models\Invoice;
use Yii;
use backend\models\search\InvoiceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * InvoiceController implements the CRUD actions for InvoiceBase model.
 */
class InvoiceController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
            ],
        ];
    }

    /**
     * Lists all InvoiceBase models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new InvoiceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $model = new Invoice();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model = new Invoice();
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * Displays a single InvoiceBase model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    /**
     * Updates an existing InvoiceBase model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->layout = false;
        $model = $this->findModel($id);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model = new Invoice();
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing InvoiceBase model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the InvoiceBase model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Invoice the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Invoice::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/invoice/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Invoice */
/* @var $form yii\widgets\ActiveForm */
?>

<?php
$this->registerJs(
    '$("document").ready(function(){
            $("#new_invoice").on("pjax:end", function() {
            $.pjax.reload({container:"#invoices"}); 
        });
    });'
);
?>

<div class="invoice-base-form">

    <?php yii\widgets\Pjax::begin(['id' => 'new_invoice', 'enablePushState' => false]) ?>
    <?php $form = ActiveForm::begin(['options' => ['data-pjax' => true]]); ?>

    <?= $form->field($model, 'city_from')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'city_to')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'recipient')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->dropDownList(\common\models\Invoice::getStatusLabels()) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <?php \yii\widgets\Pjax::end(); ?>

</div>

backend/views/invoice/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\InvoiceSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="invoice-base-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'city_from') ?>

    <?= $form->field($model, 'city_to') ?>

    <?= $form->field($model, 'recipient') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/invoice/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\base\InvoiceBase */

$this->title = 'Создать накладную';
$this->params['breadcrumbs'][] = ['label' => 'Invoice Bases', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="invoice-base-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/invoice/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\InvoiceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model common\models\Invoice */

$this->title = 'Накладные';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="invoice-base-index">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php
        \yii\bootstrap\Modal::begin([
            'header' => '<h2>Создать накладную</h2>',
            'toggleButton' => [
                'label' => 'Создать накладную',
                'tag' => 'a',
                'class' => 'btn btn-success',
            ],
        ]);
        echo $this->render('_form', [
            'model' => $model,
        ]);
        \yii\bootstrap\Modal::end();
        ?>
    </p>

    <?php
    \yii\bootstrap\Modal::begin([
        'header' => '<h2>Изменить накладную</h2>',
        'id' => 'modal',
    ]);
    echo "<div id='modalContent'></div>";
    \yii\bootstrap\Modal::end();
    ?>

    <?php
    $this->registerJs("
        $(function () {
            $('body').on('click', 'button.btn-update', function () {
             var container = $('#modalContent');
      
             container.html('Please wait, the data is being loading...');
                $('#modal').modal('show')
                .find('#modalContent')
                .load($(this).attr('value'));
            });
        });
    ")
    ?>

    <?php \yii\widgets\Pjax::begin(['id' => 'invoices']) ?>
    <?= GridView::widget(['dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'city_from',
            'city_to',
            'recipient',
            [
                'attribute' => 'status',
                'value' => 'statusLabel',
                'filter' => \common\models\Invoice::getStatusLabels()
            ],

            ['class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => ['update' => function ($url, $dataProvider, $key) {
                    return Html::button('<span class="glyphicon glyphicon-pencil"></span>', ['value' => \yii\helpers\Url::to(['invoice/update', 'id' => $dataProvider->id]),
                        'class' => 'btn-update',
                        'data-pjax' => '0',]);
                },
                ],
            ],
        ],
    ]); ?>
    <?php \yii\widgets\Pjax::end() ?>
</div>

backend/views/invoice/update.php
<?php

/* @var $this yii\web\View */
/* @var $model common\models\base\InvoiceBase */

echo $this->render('_form', [
    'model' => $model,
]);

backend/views/invoice/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\base\InvoiceBase */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Invoice Bases', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="invoice-base-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'city_from',
            'city_to',
            'recipient',
            'statusLabel',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>